### PR TITLE
Fix pry v0.14 compatibility

### PR DESCRIPTION
**Pull request by stanhu**
See https://github.com/deivid-rodriguez/pry-byebug/pull/386

### CODE REVIEW

**Comment by stanhu** [comment]
Hmm, still getting:

```
  1) Pry::Shell has a version number
     Failure/Error: @pry = Pry::REPL.start_without_pry_byebug(frame._binding, Pry::Shell.active_shell_options)

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./lib/pry/shell/patches/pry_byebug.rb:41:in `start_new_pry_session'
     # ./lib/pry/shell/patches/pry_byebug.rb:28:in `block in resume_pry'
     # ./lib/pry/shell/patches/pry_byebug.rb:27:in `resume_pry'
     # ./spec/pry/shell_spec.rb:6:in `block (2 levels) in <top (required)>'
```

**Comment by stanhu** [comment]
Still trying to get this to work. @meinac Can you take a look?

**Comment by meinac** [comment]
Thanks for working on this @stanhu! I've merged #15, could you please check if that fixed the issue?

**Comment by stanhu** [comment]
@meinac I'm not sure if I'm doing this right, but `pry-shell` doesn't seem to show any available sessions.

**Comment by meinac** [comment]
> I'm not sure if I'm doing this right, but pry-shell doesn't seem to show any available sessions.

Are you setting the breakpoint with `binding.pry_sheel`?

**Comment by meinac** [comment]
Closing as fixed by #15. Thanks @stanhu!

**Pull request closed without merging**
